version: '3'

services:
  symfony:
    build: docker/symfony
    image: yolocms-symfony
    ports:
      - "8181:8080"
    volumes:
      - ./src/admin:/home/www-data
      - ./src/public:/home/www-data/build
  web:
    build: docker/web
    image: yolocms-web
    ports:
      - "8182:80"
    volumes:
      - ./src/public:/home/www-data
