FROM php:8.1.12-zts-alpine3.16 AS yolocms-symfony
RUN apk add --no-cache libxml2-dev bash
RUN docker-php-ext-install simplexml
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.alpine.sh' | bash
RUN apk add symfony-cli
RUN symfony server:ca:install
EXPOSE 8080
WORKDIR /home/www-data
ENTRYPOINT ["symfony", "server:start", "--port=8080"]